# Copyright 2025 Canonical Ltd.
# See LICENSE file for licensing details.

"""Component to manage the Istio ambient relations."""

from charms.istio_beacon_k8s.v0.service_mesh import ServiceMeshConsumer
from charms.istio_ingress_k8s.v0.istio_ingress_route import (
    BackendRef,
    HTTPPathMatch,
    HTTPPathMatchType,
    HTTPRoute,
    HTTPRouteMatch,
    IstioIngressRouteConfig,
    IstioIngressRouteRequirer,
    Listener,
    PathModifier,
    PathModifierType,
    ProtocolType,
    URLRewriteFilter,
    URLRewriteSpec,
)
from ops import ActiveStatus, StatusBase

from charmed_kubeflow_chisme.components import Component


class AmbientIngressRequirerComponent(Component):
    """Component to manage relations over the service-mesh and istio-ingress-route endpoints."""

    def __init__(
        self,
        *args,
        service_name: str,
        port: int,
        path_prefix: str,
        url_rewrite: str,
        relation_name: str = "istio-ingress-route",
        **kwargs,
    ):
        super().__init__(*args, **kwargs)

        self.relation_name = relation_name
        self.service_name = service_name
        self.port = port
        self.path_prefix = path_prefix
        self.url_rewrite = url_rewrite

        self.ingress = IstioIngressRouteRequirer(
            self._charm,
            relation_name=self.relation_name,
        )

        self._configure_ingress()

        self._mesh = ServiceMeshConsumer(self._charm)

    def _configure_ingress(self):
        # Define listeners - names are auto-generated by the charm
        http_listener = Listener(port=80, protocol=ProtocolType.HTTP)

        config = IstioIngressRouteConfig(
            model=self._charm.model.name,  # Requirer's namespace where services live
            listeners=[http_listener],
            http_routes=[
                HTTPRoute(
                    name="http-route",
                    listener=http_listener,
                    matches=[
                        HTTPRouteMatch(
                            path=HTTPPathMatch(
                                type=HTTPPathMatchType.PathPrefix, value=self.path_prefix
                            ),
                        )
                    ],
                    filters=[
                        URLRewriteFilter(
                            urlRewrite=URLRewriteSpec(
                                path=PathModifier(
                                    type=PathModifierType.ReplacePrefixMatch,
                                    value=self.url_rewrite,
                                )
                            )
                        )
                    ],
                    backends=[BackendRef(service=self.service_name, port=self.port)],
                ),
            ],
        )
        self.ingress.submit_config(config)

    def get_status(self) -> StatusBase:
        """Return the status of the component."""
        return ActiveStatus()
