name: "tagged-release"

on:
  push:
    tags:
      - "v*"

jobs:
  tests:
    name: Run Tests
    uses: ./.github/workflows/tests.yaml

  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-22.04"
    needs: tests

    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build package
        run: python -m build

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          draft: true
          files: |
            dist/*
